### ISSUE TITLE
compile shader get "internal linking error.      undefined"

### ISSUE THREAD

**Issue by GuoLei1990** [MicrosoftEdge/WebGL#6]
when  i compile a shader  in windows mobile edge broswer of lumia 930 get this. I do not know why but when I reduce the function's  loop times, for example from ( for(int i=1;i<4;i++) ) to (( for(int i=1;i<3;i++) )),this error can fix. so  i think   the shader code length has limit,maybe is  the  HLSL shader mode 2.0 limit?but   in andorid  or IOS any browser(direction use OPENGLES2.0)  do not have this problem.  if  really this reason if  can use shader mode3.0 in good GPU(like lumia 930) when expression WEBGL

**Comment by molant** [comment]
@gl3336563 this issue should be opened in https://issues.microsoftedge.com and with the code formatted or attaching the files to have a faster response.

Thanks!

**Comment by GuoLei1990** [comment]
OK Thanks
