### ISSUE TITLE
Why not open source the whole thing?

### ISSUE THREAD

**Issue by WolfieWerewolf** [MicrosoftEdge/WebGL#7]
Dear Microsoft,

For years I have worked side by side with you not just as business partners but at your HQ in Reading, UK and lecturing at Victoria... You seem to be moving in the right direction, I even respected the "say Bing rule"... but until your browsers stop being a black box and we can see what's going on inside, embed it in whatever we want and run it on any platform, not just Windows, you will never win the browser war.  Open it up, let it roam free like the buffalo and let the community do what the community does best and work for you, for free.

**Comment by molant** [comment]
> While we don’t currently plan to fully open-source Microsoft Edge or EdgeHTML, we understand and value the importance of being more open with our roadmap and our core technologies. Recently, we open-sourced Chakra, the JavaScript engine that powers Microsoft Edge. We’re also making changes to support a more open browser with initiatives like our open roadmap on Microsoft Edge Platform Status, giving more access to our engineers through social media, and collaborating with the major rendering engine contributors, like Adobe, through a shared source program. We’re committed to being even more transparent with the engineering of Microsoft Edge in the future.

https://developer.microsoft.com/en-us/microsoft-edge/platform/faq/

**Comment by WolfieWerewolf** [comment]
Hi, thanks for the reply.  That sounds great but for the moment WebGL performance in Edge is substantially worse than in other browsers.  Unless I can see the source I can't troubleshoot it, if I can't troubleshoot it then Edge either falls out of the supported browsers list for my apps or goes to the bottom.... That's the net result of these decisions.
